#!/usr/bin/env bash
# Reproduction script for run 20260518T172818Z_mouse_skull_d534f1.
# Generated by run_telemetry.RunLogger.write_replay().
#
# Verify that:
#   1. Your remote Slicer instance has a volume whose
#      sha256_voxels matches inputs.json's sha256_voxels.
#   2. SLICER_WEBSERVER_URL points at a Slicer instance with
#      the SlicerNNInteractive plugin running.
set -euo pipefail
cd "$(dirname "$0")/../.."  # back to repo root

export SLICER_WEBSERVER_URL="https://http-149-165-152-225-2016.proxy-js2-iu.exosphere.app/"
export NNI_REMOTE_URL="https://http-149-165-152-225-1527.proxy-js2-iu.exosphere.app/"
export OPENAI_API_KEY="<<set me>>"

python3 ".github/scripts/slicer_remote_bright_seed.py" \
    --volume IMPC_sample_data \
    --intensity-percentile 99.5 \
    --max-candidates 50000 \
    --max-steps 3 \
    --min-delta 200 \
    --patience 3 \
    --max-explosion-frac 0.4 \
    --reset-first \
    --out-dir runs/replay_20260518T172818Z_mouse_skull_d534f1 \
    --label "mouse_skull"
